application: event-horizon-cssi
version: demo2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/*
  static_dir: static

- url: .*
  script: main.app

- url: /_ah/login_required
  script: do_openid_login.app

- url: /youraccount/.*
  script: accounts.app
  login: required
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
